# Generated by Django 2.2 on 2020-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='title',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
