# Generated by Django 2.2 on 2020-07-30 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200730_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 16, 33, 44, 488359)),
        ),
    ]
